import Image from "next/image";

const About = () => {
  return (
    <section className="container pt-[60px] md:mt-[80px] lg:mt-[107px]">
      <h2 className="md:w-[269px] text-white font-black text-[40px] md:text-6xl lg:text-[120px] leading-10 md:leading-[60px] lg:leading-[120px] uppercase mb-4">
        A story that started with{" "}
        <span className="text-rose-500">
          one simple <br className="md:hidden" />
          ape
        </span>
      </h2>

      <p className="md:w-[276px] text-right font-messinaSans text-white text-base lg:text-2xl font-normal uppercase  mb-9 md:mb-[68px]">
        WHO GOT <br className="md:hidden" />
        FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF
        ESCAPING AND DYNAMIC JOURNEY ON THE
        <br className="hidden md:block" /> YACHT
      </p>

      <div className="md:w-[269px] flex flex-col items-center justify-center gap-4 md:gap-6 mb-6 md:mb-9">
        <svg className="h-6 w-6 lg:h-9 lg:w-9">
          <use xlinkHref="/icons/sprite.svg#icon-cross"></use>
        </svg>

        <p className="text-center font-messinaSans text-white text-base lg:text-2xl font-normal uppercase">
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </p>
      </div>

      <Image
        src="/images/about.png"
        alt="Ape with glasses"
        width={610}
        height={822}
        className="w-[216px] h-[292px] md:w-[313px] md:h-[422px] lgw-[610px] lg:h-[822px]"
      />

      <div className="bg-rose-500 h-[52px]"></div>
    </section>
  );
};

export default About;
